apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-apps
  template:
    metadata:
      labels:
        app: mlops-apps
    spec:
      containers:
      - name: mlops-apps
        image: us-central1-docker.pkg.dev/consummate-gift-458313-s6/mlops-apps/mlops-apps:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
